In [28]:
list1 = []
list1.append(1)
list1.append(1)
list1.append(1)
print(list1)

[1, 1, 1]


In [ ]:
import pandas as pd


df = pd.read_csv("probabilites.csv")

# Create the dictionary as described
probabilites = {}

for index, row in df.iterrows():
    # Separation des strings
    predateur, proie = row['Distance proie - prédateur (m)'].split('->')
    
    for col in df.columns[1:]:
        clé = (str(col) if col.isdigit() else col, predateur, proie) 
        # Determination de valuer pour chaque clé
        probabilites[clé] = row[col]

probabilites

In [7]:
import math

math.exp((3-1)/2)    

2.718281828459045

In [9]:
import numpy as np 

print(np.array([1,0,0,0,2]) <2 )


[ True  True  True  True False]


In [80]:
import numpy as np
import random
list_predators = ['p1', 'p2', 'p3', 'p4', 'p5', 'p6' , 'p7', 'p8']
array_predators = np.array(list_predators)
distances = [1,2,3,4,5,6,7,8]
filtered_list = np.array(distances) < 5

for i, valeur in enumerate(filtered_list):
     if valeur == 1:
        probabilite = 0.5
        if random.random() < probabilite:
            filtered_list[i] = 0

print(array_predators[filtered_list])

['p1' 'p4']


In [58]:
print(len(filtered_list[filtered_list]))

0


In [74]:
posicao = [np.array([3,4]), np.array([20,21]), np.array([2,34])]
posicao = np.array(posicao)
posicao = posicao[posicao[:,0] < 10]
posicao = posicao[posicao[:,1] <10]
posicao

array([[3, 4]])

In [ ]:
## 15:07 esse código manteve o gameboard estático só para ver onde estava cada coisa

class GameBoard(tk.Tk):
    def __init__(self, champ, cell_size=10):
        super().__init__()
        self.title("Prédateur-Proie Simulation")

        self.champ = champ
        self.rows = champ.height
        self.cols = champ.width
        self.cell_size = cell_size

        self.canvas = tk.Canvas(
            self, height=self.rows * cell_size, width=self.cols * cell_size)
        self.canvas.pack()

        self.draw_grid()
        self.place_objects()

    def draw_grid(self):
        for i in range(self.rows):
            self.canvas.create_line(
                0, i * self.cell_size, self.cols * self.cell_size, i * self.cell_size)
        for i in range(self.cols):
            self.canvas.create_line(
                i * self.cell_size, 0, i * self.cell_size, self.rows * self.cell_size)

    def place_objects(self):
        for predator in self.champ.predateurs:
            self.draw_object(predator.position, 'red')

        for prey in self.champ.proies:
            self.draw_object(prey.position, 'blue')

        for haie in self.champ.obstacles:
            self.draw_object(haie.position, 'green')

    def draw_object(self, position, color):
        x, y = position
        self.canvas.create_rectangle(x * self.cell_size, y * self.cell_size,
                                     (x + 1) * self.cell_size, (y + 1) * self.cell_size, fill=color)

In [ ]:
def is_dead(self, prey, list_preys):
        '''Essa é para verificar se matou uma presa e muda o status do predador. Recebe a 
        presa específica, e vai receber também champ.proies para conseguir deletar uma 
        presa específcia depois que ela morrer.
        A condição de posições iguais tem que estar necessariamente antes de começar o
        código para poder fazer esass coisas.'''
        if prey != None:
            if self.position[0] == prey.position[0] and self.position[1] == prey.position[1]:
                if prey in list_preys:
                    list_preys.remove(prey)
                self.is_satiated = True
                self.without_meat = 0
                self.identified_prey = False
               
        else:
            pass

In [91]:
import random 
positions = np.array([np.array([1,2]), np.array([7,8]), np.array([12,22])])
aleatoire = np.random.randint(0, len(positions))
positions[aleatoire]


array([7, 8])

In [94]:
np.array([3,4]) + np.array(np.array([1,2]))

array([4, 6])

In [3]:
import pandas as pd

df = pd.read_csv("probabilites.csv")
probabilites = {}
dic_distances = {}

for index, row in df.iterrows():
    # Separation des strings
    predateur, proie = row['Distance proie - prédateur (m)'].split('->')

    for col in df.columns[1:]:
        clé = (str(col) if col.isdigit() else col, predateur, proie)
        # Determination de valuer pour chaque clé
        probabilites[clé] = row[col]

print(probabilites)

{('1', 'coyote', 'écureuil'): 0.5, ('2', 'coyote', 'écureuil'): 0.45, ('3', 'coyote', 'écureuil'): 0.4, ('4', 'coyote', 'écureuil'): 0.35, ('5', 'coyote', 'écureuil'): 0.3, ('6', 'coyote', 'écureuil'): 0.25, ('7', 'coyote', 'écureuil'): 0.2, ('8', 'coyote', 'écureuil'): 0.07, ('9+', 'coyote', 'écureuil'): 0.03, ('15+', 'coyote', 'écureuil'): 0.0, ('1', 'coyote', 'chien de prairie'): 0.7, ('2', 'coyote', 'chien de prairie'): 0.6, ('3', 'coyote', 'chien de prairie'): 0.55, ('4', 'coyote', 'chien de prairie'): 0.5, ('5', 'coyote', 'chien de prairie'): 0.4, ('6', 'coyote', 'chien de prairie'): 0.2, ('7', 'coyote', 'chien de prairie'): 0.1, ('8', 'coyote', 'chien de prairie'): 0.05, ('9+', 'coyote', 'chien de prairie'): 0.01, ('15+', 'coyote', 'chien de prairie'): 0.01, ('1', 'blaireau', 'écureuil'): 0.45, ('2', 'blaireau', 'écureuil'): 0.38, ('3', 'blaireau', 'écureuil'): 0.27, ('4', 'blaireau', 'écureuil'): 0.27, ('5', 'blaireau', 'écureuil'): 0.22, ('6', 'blaireau', 'écureuil'): 0.15, ('

In [101]:
round(2.49)

2

In [103]:
doido = (4>5)
print(doido)

False


In [21]:
import random
random.randint(0, 4)

4

In [4]:
probabilites[(str(1), 'coyote', 'écureuil')]

0.5